kind: pipeline
type: kubernetes
name: default

# disable apparmor so buildah isn't prevented from mounting with fuse-overlayfs
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/build: unconfined

steps:
  - name: build
    image: quay.io/buildah/stable:latest
    environment:
      # get registry credentials from orgsecrets
      REGISTRY_USERNAME:
        from_secret: registry_username
      REGISTRY_PASSWORD:
        from_secret: registry_password
    commands:
      - buildah login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.hubbe.club
      - buildah bud --tag registry.hubbe.club/music:mpd mpd
      - buildah bud --tag registry.hubbe.club/music:mpdscribble mpdscribble
      - buildah push registry.hubbe.club/music:mpd
      - buildah push registry.hubbe.club/music:mpdscribble
    resources:
      requests:
        cpu: 100
        memory: 100MiB
      limits:
        cpu: 500
        memory: 500MiB
